-- AlterTable
ALTER TABLE "Zone" ALTER COLUMN "name" DROP DEFAULT,
ALTER COLUMN "hoursFR" DROP DEFAULT,
ALTER COLUMN "fullPZ" DROP DEFAULT,
ALTER COLUMN "pz35Plus" DROP DEFAULT,
ALTER COLUMN "efficiency" DROP DEFAULT;
