-- Drop old description column and add detailed fields
ALTER TABLE "Zone" DROP COLUMN "description";
ALTER TABLE "Zone" ADD COLUMN "name" TEXT NOT NULL DEFAULT '';
ALTER TABLE "Zone" ADD COLUMN "hoursFR" DOUBLE PRECISION NOT NULL DEFAULT 0;
ALTER TABLE "Zone" ADD COLUMN "fullPZ" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "Zone" ADD COLUMN "pz35Plus" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "Zone" ADD COLUMN "efficiency" DOUBLE PRECISION NOT NULL DEFAULT 0;
